import os
import json
from models import ExecutionProfile
from orchestrator import RobAIAgentRuntime
from brain import GroqBrain

def main():
    try:
        brain = GroqBrain(model_name="qwen/qwen3.8-27b")
    except ValueError as ve:
        print(f"Initialization Error: {ve}")
        return

    user_id = "user_dev_01"
    agent = RobAIAgentRuntime(user_id=user_id, profile=ExecutionProfile.STANDARD)

    user_query = "Find my available time slots tomorrow and create a lunch meeting with Sarah at 12 PM."
    print(f"User Goal: '{user_query}'")

    print("\n--- Step 1: Generating Plan via Groq API ---")
    raw_plan_from_groq = brain.generate_plan(user_query)
    print("Raw Structured Plan Generated by Groq Brain:")
    print(json.dumps(raw_plan_from_groq, indent=2))

    print("\n--- Step 2: Executing First Pass through Governor Runtime ---")
    res1 = agent.run_pipeline(raw_plan_from_groq)

    if res1["status"] == "PAUSED_AWAITING_APPROVAL":
        proposal_id = res1["proposal_id"]
        description = res1["exact_description"]
    
        print("\n" + "="*50)
        print(" ACTION REQUIRES HUMAN APPROVAL")
        print(f"Proposal ID : {proposal_id}")
        print(f"Details     : {description}")
        print("="*50)
    
        # Prompt the real user in real time
        user_choice = input("\nDo you authorize this action? (y/N): ").strip().lower()
    
        if user_choice == 'y':
            token = agent.approval_engine.approve_proposal(proposal_id)
            print(f"\n[APPROVAL GRANTED] Issued Token: {token}")
        
            print("\n--- Resuming Pipeline with Single-Use Approval Token ---")
            res2 = agent.run_pipeline(raw_plan_from_groq, user_approved_token=token)
            print("\nFinal Result:", json.dumps(res2, indent=2))
        else:
            print("\n[APPROVAL DENIED] Action aborted by user.")

    

if __name__ == "__main__":
    main()
