from pydantic import ValidationError
from models import StructuredPlan

class PlanValidationError(Exception):
    pass

def validate_llm_plan(raw_plan_json: dict) -> StructuredPlan:
    try:
        validated_plan = StructuredPlan.model_validate(raw_plan_json)
        return validated_plan
    except ValidationError as e:
        raise PlanValidationError(f"Invalid plan generated by LLM: {e}")
